server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cloudflylan/lanye.git #github上面的git仓库地址
          #搜索目录
          search-paths:
            - lanye
          username: cloudflylan
          password: lan4582567
          skip-ssl-validation: false
      #读取分支
      label: main
  rabbitmq:
    host: 192.168.1.105
    port: 15672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud-gateway-service