server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.88:8848
    sentinel:
      transport:
        #dashboard: 192.168.1.88:8080
        dashboard: localhost:8081
        port: 8719
        clientIp: localhost
      filter:
        url-patterns: /**
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.88:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'