server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: feign-consumer80
spring:
  application:
    name: cloud-feign-consumer80

ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
logging:
  level:
    com.lanye.springcloud.service.PaymentFeignService: debug
